### ISSUE TITLE
I hereby challenge thee to a benchmark race!

### ISSUE THREAD

**Issue by dominictarr** [deanlandolt/bytewise#23]
I am posting this issue to officially challenge bytewise contributors to a benchmark race.
🐎 🏇 🏁 🏅 

I am using bytewise for numerous leveldb indexes inside of http://scuttlebutt.nz/ and it has recently come to my attention that bytewise encoding is actually a performance bottleneck (in particular, affecting the user experience at first use! - a database is pulled down and and indexed, and it takes too long)

decode performance is pretty good, but I can beat encode perf 4x (my usecase is more bound to encode perf) 

```
bytewise.encode 24274
bytewise.decode 86983
charwise.encode 107742
charwise.decode 74076
```
https://github.com/dominictarr/charwise does basically what bytewise does, but it does it with strings which are pretty optimized for concatination.

**Comment by deanlandolt** [comment]
Apologies -- I haven't been using bytewise much lately and my github notifications got buried in a flood of work-related notifications.

As for perf, when I profiled this way back when when using in a sublevel-like workload, the most noticeable perf hit was the recursive encode/decode of binary buffers to escape null bytes. Of course, there's no particular reason binary has to be encoded this way -- you probably don't *really* need true lexicographical order for blobs of bytes anyway. If you encode bytes with a length-prefix you still get a sensible ordering for blobs (short-lex order), and decoding can just slurp data right back in.

But meh. For most workflows `charwise` is almost certainly all you need. Where I was ultimately aiming to take `bytewise` was to allow more exotic, powerful types to be mixed in in a coherent way (e.g. using a lexicographical continued fraction representation), which would allow interval types and arbitrary-precision arithmetic in a way that mixes well with floating point numeric. Essentially, to define a type system strictly based on canonicalized representations that allows for practically free tests for poset relations like containment.

AFAICT `charwise` is the way to go for almost all workflows. I'll add a note to the README to direct folks in that direction.

**Comment by deanlandolt** [comment]
Added note to README re: using `charwise` where possible. No sense in trying to bench bytewise vs. charwise -- the buffer manipulation bytewise is doing is just inherently slower than working w/ immutable string values. IIRC it'd be _possible_ to rewrite `bytewise` into a little regex-based parser over ascii-8 strings, but I haven't ever done that for fear of the unicode rabbitholes I'm sure to fall into.

**Comment by dominictarr** [comment]
oh please don't direct them to charwise yet! It's only half working currently! I'm still using bytewise in practice
